name: Cypress Tests

# Indica cuándo ejecutar el workflow (en este caso, en cada push o pull request a la rama main)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.7.1"

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test
        env:
          CI: true
