name: Cypress Tests

on:
  schedule:
    - cron: "0 20 * * 1" # Ejecuta el workflow todos los lunes a las 17hs (20hs UTC)
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.7.1"

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test
        env:
          CI: true

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: reports/*
